In [312]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [313]:
# Loading the dataset
df = pd.read_csv(r'Data\Raw\flats.csv')
df.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
2790,2 BHK Flat in Sector 95 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,AWHO Shanti Vihar4.0 ★,82 Lac,"₹ 9,879/sq.ft.",Super Built up area 1400(130.06 sq.m.)Carpet a...,2 Bedrooms,2 Bathrooms,3+ Balconies,Study Room,"Sector 95 Gurgaon, Gurgaon, Haryana",13rd of 19 Floors,East,0 to 1 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",Gated community\nTwo fully functional swimming...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Management5 out of 5', 'Green Area5 out of 5...",X62867284
1789,3 BHK Flat in Sector 90 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,DLF New Town Heights 13.9 ★,1.3 Crore,"₹ 6,735/sq.ft.",Super Built up area 1930(179.3 sq.m.)Built Up ...,3 Bedrooms,3 Bathrooms,3+ Balconies,"Pooja Room,Servant Room","5555, Sector 90 Gurgaon, Gurgaon, Haryana",10th of 19 Floors,South,1 to 5 Year Old,"['Manish Gallexie 91', 'NH-8 IMT Manesar', 'RH...",This 3 bhk flat is located in dlf new town hei...,"['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4 out of...",I69266172
67,3 BHK Flat in Sector 57 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,BPTP Freedom Park Life4.0 ★,2.5 Crore,"₹ 11,111/sq.ft.",Super Built up area 2250(209.03 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sector 57 Gurgaon, Gurgaon, Haryana",9th of 15 Floors,NaN,5 to 10 Year Old,"['Presidium School Gurgoan', 'Manav Rachna Sch...",We are the proud owners of this 3 bhk apartmen...,[],NaN,"['Green Area5 out of 5', 'Amenities5 out of 5'...",S68706654
2481,3 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Smart World Orchard,2.57 Crore,"₹ 15,766/sq.ft.",Carpet area: 1630 (151.43 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",3rd of 4 Floors,North-East,Under Construction,"['Sector 55-56 Metro station', 'Bestech Centra...",This beautiful 3 bhk flat in sector-61 gurgaon...,"['3 AC', '1 Chimney', '1 Modular Kitchen', '1 ...",['Lift(s)'],NaN,S66339050
1421,2 BHK Flat in Sector 37C Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apex Our Homes,35 Lac,"₹ 3,783/sq.ft.",Super Built up area 925(85.94 sq.m.)Built Up a...,2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"753, Sector 37C Gurgaon, Gurgaon, Haryana",7th of 11 Floors,East,1 to 5 Year Old,"['Elvedor Mall', 'MDS Public School', 'K.D. Ho...",Check out this 2 bhk apartment for sale in ape...,"['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '2 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Environment5 out of 5', 'Lifestyle4 out of 5...",P70095968

In [314]:
# Check for the shape of the dataset
df.shape

(3017, 20)

In [315]:
# Check for the data types of the columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3017 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3017 non-null   object
 1   link             3017 non-null   object
 2   society          3016 non-null   object
 3   price            3007 non-null   object
 4   area             3004 non-null   object
 5   areaWithType     3008 non-null   object
 6   bedRoom          3008 non-null   object
 7   bathroom         3008 non-null   object
 8   balcony          3008 non-null   object
 9   additionalRoom   1694 non-null   object
 10  address          3002 non-null   object
 11  floorNum         3006 non-null   object
 12  facing           2127 non-null   object
 13  agePossession    3007 non-null   object
 14  nearbyLocations  2913 non-null   object
 15  description      3008 non-null   object
 16  furnishDetails   2203 non-null   object
 17  features         2594 non-null   object
 18  rating           2676 non-null   object
 19  property_id      3008 non-null   object
dtypes: object(20)
memory usage: 471.5+ KB

In [316]:
# Check for the duplicate rows in the dataset
df.duplicated().sum()

np.int64(0)

In [317]:
# Check for the missing values in the dataset
df.isnull().sum()

property_name         0
link                  0
society               1
price                10
area                 13
areaWithType          9
bedRoom               9
bathroom              9
balcony               9
additionalRoom     1323
address              15
floorNum             11
facing              890
agePossession        10
nearbyLocations     104
description           9
furnishDetails      814
features            423
rating              341
property_id           9
dtype: int64

In [318]:
# Check for the non-relevant columns in the dataset and drop them
df.drop(["link","property_id"], inplace =True, axis=1)
df.shape

(3017, 18)

In [319]:
# Replace name of area column to price_per_sqft
df.rename(columns = {'area':'price_per_sqft'}, inplace = True)

In [320]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [321]:
df.society.value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Orchard                                  32
Smart World Gems                                     32
Paras Dews                                           31
DLF The Ultima4.0 ★                                  31
DLF Regal Gardens3.9 ★                               30
M3M Woodshire4.0 ★                                   29
Shree Vardhman Flora3.8 ★                            29
La Vida by Tata Housing                              28
Signature Global Solera3.7 ★                         28
Godrej Nature Plus                                   27
Emaar Gurgaon Greens4.1 ★                            25
BPTP Terra3.8 ★                                      25
Vatika Gurgaon 213.7 ★                               24
Experion The Heartsong3.9 ★                          24
DLF New Town Heights 13.9 ★                          24
Eldeco Accolade3.8 ★                                 24
Bestech Park View Residency3.9 ★                     23
Tata Primanti4.1 ★                                   22
Emaar Palm Gardens4.1 ★                              22
M3M Heights                                          22
ATS Triumph3.9 ★                                     22
Sare Crescent Parc3.5 ★                              21
ROF Ananda                                           21
Experion Windchants3.8 ★                             20
Godrej 1014.0 ★                                      20
Antriksh Heights3.7 ★                                19
Sare Homes                                           19
Mapsko Mount Ville4.1 ★                              18
ATS Tourmaline3.9 ★                                  18
Indiabulls Centrum Park3.7 ★                         18
Supertech Araville                                   18
Ambience Creacions                                   18
CHD Avenue 713.6 ★                                   18
Sobha City                                           18
Conscient Heritage Max4.3 ★                          17
GLS Arawali Homes3.8 ★                               17
M3M Golfestate4.4 ★                                  17
M3M Skywalk                                          17
Godrej Summit3.7 ★                                   17
Pareena Coban Residences                             17
M3M Merlin3.7 ★                                      16
Bestech Park View Grand Spa4.3 ★                     16
HCBS Sports Ville3.6 ★                               16
Godrej Oasis3.9 ★                                    15
Ansal Heights 86                                     15
Emaar MGF The Palm Drive4.1 ★                        15
Umang Monsoon Breeze                                 15
Vatika The Seven Lamps3.8 ★                          14
The Close North4.0 ★                                 14
MVN Athens3.7 ★                                      14
Indiabulls Enigma                                    14
Ireo Victory Valley4.1 ★                             14
Corona Optus3.9 ★                                    14
Orchid Petals4.1 ★                                   14
Ramsons Kshitij3.7 ★                                 14
Ireo Skyon4.0 ★                                      14
Imperia The Esfera                                   14
DLF The Primus3.9 ★                                  14
Umang Winter Hills3.9 ★                              14
Central Park Flower Valley                           13
Bestech Park View Ananda4.2 ★                        13
Puri Emerald Bay3.7 ★                                13
Ireo The Corridors                                   13
Alpha Corp GurgaonOne 844.0 ★                        11
SBTL Caladium                                        11
TARC Maceo3.8 ★                                      11
Raheja Vedaanta3.6 ★                                 11
Breez Global Hill View                               11
M3M Soulitude                                        11
DLF The Skycourt4.2 ★                                11
Adani M2K Oyster Grande3.9 ★                         11
Godrej Aria3.8 ★                                     11
Pyramid Urban Homes 2                                10
Pivotal Devaan                                       10
Zara Aavaas                                          10
Signature Global Synera3.4 ★                         10
Ramprastha The Edge Towers3.5 ★                      10
Godrej Air                                           10
DLF New Town Heights 24.0 ★                          10
ATS Kocoon                                           10
Emaar MGF Palm Hills4.0 ★                            10
Breez Global Heights4.2 ★                            10
Puri Diplomatic Greens4.0 ★                          10
Capital Residences 360                               10
Parsvnath Green Ville3.9 ★                            9
Bestech Park View Sanskruti4.2 ★                      9
ILD Greens4.1 ★                                       9
Pareena Mi Casa                                       9
Microtek Greenburg3.8 ★                               9
Vatika City4.1 ★                                      9
AIPL The Peaceful Homes3.9 ★                          9
ss                                                    8
GLS Avenue 51                                         8
Assotech Blith                                        8
M3M Capital                                           8
Birla Navya                                           8
AVL 36 Gurgaon3.7 ★                                   8
Orris Aster Court Premier                             8
Emaar Digihomes                                       8
The Lions CGHS                                        8
Tulip Ivory3.5 ★                                      8
Bestech Altura                                        8
M3M Skycity                                           8
Vatika Lifestyle Homes3.8 ★                           8
Emaar Imperial Gardens3.8 ★                           7
Ireo The Grand Arch4.0 ★                              7
Orris Carnation Residency3.7 ★                        7
AIPL Zen Residences                                   7
Ansal Housing Highland Park                           7
Signature Global Orchard Avenue3.6 ★                  7
Vipul Lavanya3.9 ★                                    7
Sare Green ParC Phase 3                               7
Trisara Our Homes 3                                   7
Signature Andour Heights3.8 ★                         7
Signature Global City                                 7
Sare Crescent Parc Royal Greens Phase 1               7
Mapsko Casa Bella3.8 ★                                7
HSIIDC Sidco Aravali                                  6
Pioneer Araya3.8 ★                                    6
Bestech Park View City4.1 ★                           6
Kiran Residency                                       6
BPTP Astaire Gardens3.7 ★                             6
Sidhartha NCR One Phase 14.2 ★                        6
Signature Global Park 4                               6
Suncity Vatsal Valley                                 6
Supertech Hues                                        6
M3M Sierra 68                                         6
Signature The Roselia3.6 ★                            6
Ashiana Mulberry                                      6
Mapsko Royale Ville3.7 ★                              6
Bestech Park View Spa Next4.0 ★                       6
DLF Regency Park 13.6 ★                               6
Signature Global City 63A                             6
Pyramid Urban                                         6
Shapoorji Pallonji Joyville Gurugram                  6
Greenopolis                                           6
Hero Homes                                            6
Parsvnath Exotica3.7 ★                                6
M3M The Marina4.0 ★                                   5
Signature Global the Millennia                        5
DLF Regency Park 24.0 ★                               5
Godrej Habitat                                        5
Central Park Flower Valley Aqua Front Towers          5
Tulip Monsella                                        5
Signature Global City 92                              5
Pioneer Park3.8 ★                                     5
Satya The Hermitage3.5 ★                              5
Silverglades The Melia                                5
Essel Towers                                          5
Vatika Sovereign Park                                 5
Krisumi Waterfall Residences                          5
Signature Global Grand IVA3.9 ★                       5
ATS Marigold                                          5
Ireo Uptown4.1 ★                                      5
Pareena Laxmi Apartments3.6 ★                         5
Emaar MGF Emerald Estate3.8 ★                         5
Signature Global City 81                              5
DLF Park Place4.1 ★                                   5
Vatika City Homes3.9 ★                                5
Central Park Resorts4.4 ★                             5
Conscient Elevate                                     5
Apna Enclave                                          5
Green Court3.7 ★                                      5
Adani Brahma Samsara Vilasa                           5
Ashiana Anmol3.5 ★                                    5
Signature Global City 37D Ph 2                        5
Signature The Serenas                                 4
Tata Gurgaon Gateway3.8 ★                             4
Godrej Icon                                           4
Unitech Vistas                                        4
Orris Aster Court                                     4
ILD Grand                                             4
Railway Officers RPF Society                          4
Raheja Navodaya3.6 ★                                  4
Global Hill View                                      4
Corona Gracieux                                       4
Krrish Provence Estate                                4
DLF The Skycourt                                      4
SS The Coralwood3.4 ★                                 4
Prime Habitat                                         4
Lotus Homz4.0 ★                                       4
Ramprastha Primera                                    4
Sare Petioles                                         4
Unitech Fresco3.8 ★                                   4
Emaar Palm Heights                                    4
Ramprastha Skyz                                       4
Godrej Frontier3.7 ★                                  4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
DLF New Town Heights3.7 ★                             4
Tulip Purple                                          3
Shree Arihant Apartment                               3
Mahindra Aura4.2 ★                                    3
Paras Quartier                                        3
ATS Kocoon4.2 ★                                       3
Puri Diplomatic Greens3.9 ★                           3
Unitech Heritage City                                 3
Shri Banke Bihari Society3.8 ★                        3
AIPL Club Residences                                  3
Ambience Lagoon3.9 ★                                  3
Vatika Independent Floors3.8 ★                        3
Raheja Atharva3.6 ★                                   3
Dhoot Time Residency4.0 ★                             3
DLF Royalton Tower                                    3
Sunischit Apartments                                  3
Unitech Uniworld Gardens3.8 ★                         3
Guru Gram Haryana CGHS4.1 ★                           3
DLF Belvedere Towers3.8 ★                             3
Unitech Sunbreeze                                     3
Krrish Florence Estate                                3
Adani Aangan Arcade                                   3
Sare Green Parc                                       3
Chintels Paradiso3.9 ★                                3
Essel Tower                                           3
The Roselia 2                                         3
Maxworth City Residences                              3
Deepak Minda                                          3
Kendriya Vihar4.1 ★                                   3
Unitech The Residences3.7 ★                           3
Sidhartha NCR One                                     3
DLF The Arbour                                        3
Whiteland Blissville                                  3
Valley View Estate                                    3
Signature Global Solera 2                             3
Raheja Sampada                                        3
Sidhartha NCR Greens4.3 ★                             3
Pivotal Riddhi Siddhi                                 3
Bestech Park View City 23.9 ★                         3
My Home                                               3
AFNHB Jalvayu Vihar3.7 ★                              3
Brisk Lumbini Terrace Homes                           3
Piedmont Taksila heights3.6 ★                         3
Siddhartha Apartment                                  3
Smriti Apartment                                      3
Vatika Xpressions                                     3
DLF Carlton Estate4.0 ★                               3
SS Almeria                                            3
Sukhshanti Apartment                                  3
DLF The Grove                                         3
Spaze Privvy The Address3.9 ★                         3
Sapphire Eighty Three                                 3
Tulip White3.5 ★                                      3
Spaze Privy3.9 ★                                      3
Tulip Lemon3.9 ★                                      3
Shri Ram Apartments                                   3
Conscient Habitat3.6 ★                                3
Satya Element One                                     3
Pyramid Elite                                         3
Apex Our Homes                                        3
Suncity Platinum Towers                               3
Spaze Privy AT43.9 ★                                  3
Sare Green Parc 2                                     3
DLF Express Greens3.9 ★                               3
Raheja Revanta                                        3
Tulip Petals3.6 ★                                     3
Godrej Nature Plus Serenity                           2
Tulip Orange3.9 ★                                     2
Supertech Hill Town                                   2
Housing Board Colony                                  2
NBCC Heights3.9 ★                                     2
Sahara Grace                                          2
Oriental Valley CHS                                   2
Suncity Avenue 76                                     2
Adani Aangan Galleria                                 2
HCBS Sports Ville                                     2
Aqua Front Towers                                     2
Ansal API Esencia3.7 ★                                2
DLF The Icon3.7 ★                                     2
Professors Enclave CGHS                               2
Paras Irene3.7 ★                                      2
Mittal Surya Vihar                                    2
Suposhaa Smartworld Orchard                           2
DLF The Belaire3.9 ★                                  2
Suncity Avenue 1023.9 ★                               2
BPTP Amstoria3.8 ★                                    2
Emaar MGF The Enclave                                 2
Vipul Belmonte3.9 ★                                   2
Bestech Park View Sanskruti4.1 ★                      2
BPTP Mansions Park Prime                              2
M3M Ikonic                                            2
The Penthouses at the Hibiscus                        2
SS Hibiscus                                           2
Viridian The Plaza 106                                2
Tulip Leaf                                            2
Tulip Violet                                          2
Vatika Emilia Floors3.7 ★                             2
Emaar MGF Palm Studios                                2
Orchid Island4.2 ★                                    2
Signature Global The Millennia 3                      2
Samaspurkunj                                          2
M3M Sky Lofts                                         2
ROF Aalayas3.8 ★                                      2
AWHO Shanti Vihar4.0 ★                                2
Residency Grand                                       2
Ganga Apartment                                       2
Raheja Atlantis3.8 ★                                  2
Ashiana Anmol                                         2
Central Park 2 Bellevue                               2
om appartments                                        2
Shapoorji Pallonji Joyville                           2
DLF The Crest3.6 ★                                    2
Today Callidora                                       2
Landmark The Residency                                2
Vasant Appartments                                    2
Maruti Vihar                                          2
Ambience Caitriona                                    2
Bhagwati Sadan                                        2
Unitech Uniworld Gardens 23.4 ★                       2
BPTP Pedestal                                         2
MRG World Ultimus                                     2
Sidhivinayak Apartments                               2
Mapsko Paradise3.9 ★                                  2
Park Royal Apartment                                  2
Ramprastha The Atrium3.4 ★                            2
Mahindra Luminare4.0 ★                                2
Suncity Heights3.7 ★                                  2
BPTP Freedom Park Life4.0 ★                           2
Jammu and Kashmir Bank Employees CGHS3.7 ★            2
Puri The Aravallis                                    2
Ansal Heights3.2 ★                                    2
Ramprastha City                                       2
M3M Urbana                                            2
Ardee City3.8 ★                                       2
Palam Vihar Society                                   2
Vatika INXT Floors                                    2
Raheja Vanya                                          2
Surendra Avenue 69                                    2
Supertech Hilltown                                    2
Tulsiani Easy in Homes                                2
Breeze Global Heights                                 2
CGHS Airport Apartment                                2
Vipul World Floors                                    2
Ansal API Celebrity Suites                            2
M3M Latitude                                          2
Apartment                                             2
Element One Service                                   2
Pioneer Urban Presidia                                2
Elan The Presidential                                 2
Bestech Spa Signature                                 2
Green Campus CHS                                      2
Lavanya Apartments                                    2
Milan CGHS 9                                          2
Silverglades Hightown Residences                      2
Dlf City                                              2
The Close South3.9 ★                                  2
lagoon apartment                                      2
Surbhi Apartment                                      1
The Center Court                                      1
Divya Apartments                                      1
Maple Heights                                         1
ikon tower baani city centre                          1

In [322]:
# Check for unique categories in the society column
df.society.value_counts().shape

(638,)

In [323]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [324]:
df.society.value_counts().shape

(604,)

In [325]:
# Check Price column and find unique values in it.
pd.set_option('display.max_rows', None)
df.price.value_counts().shape

(439,)

In [326]:
df[df['price'] == 'Price on Request']

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
25,5 BHK Flat in Sector 1 Gurgaon,the new people apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",Ground of 1 Floors,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN
1644,4 BHK Flat in Sector 50 Gurgaon,ss hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1972,1 BHK Flat in Sector 31 Gurgaon,raheja atlantis,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
2054,2 BHK Flat in Sector 79 Gurgaon,supertech araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15th of 15 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."
2357,2 BHK Flat in Sector 37D Gurgaon,the millennia 2,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2522,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
2549,3 BHK Flat in Sector-2 Sohna,supertech hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
2640,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
2959,3 BHK Flat in Sector 104 Gurgaon,godrej summit,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
2972,4 BHK Flat in Gwal Pahari,krrish provence estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
2973,4 BHK Flat in Sector 95 Gurgaon,sidhartha ncr one phase,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [327]:
df = df[df['price'] != 'Price on Request']

In [328]:
df.price.value_counts().shape

(438,)

In [329]:
# Function to convert lac into crores.
def treat_price(X):
    if type(X) == float:
        return X
    else:
        if X[1] == 'Lac':
            return round(float(X[0])/100,2)
        else:
            return round(float(X[0]),2)

In [330]:
# Use the treat_price function to convert the price column to one consistent unit that is in Crores.
df['price'] = df['price'].str.split(" ").apply(treat_price)

In [331]:
# check for the unique values in the price_per_square feet column
pd.set_option('display.max_rows', None)
df.price_per_sqft.value_counts()

price_per_sqft
₹ 10,000/sq.ft.     19
₹ 8,000/sq.ft.      16
₹ 12,500/sq.ft.     16
₹ 6,666/sq.ft.      13
₹ 5,000/sq.ft.      13
₹ 7,500/sq.ft.      12
₹ 8,333/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 12,000/sq.ft.      8
₹ 7,000/sq.ft.       8
₹ 9,000/sq.ft.       7
₹ 9,230/sq.ft.       6
₹ 8,928/sq.ft.       6
₹ 5,500/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 11,111/sq.ft.      6
₹ 6,578/sq.ft.       6
₹ 8,888/sq.ft.       6
₹ 8,205/sq.ft.       5
₹ 7,692/sq.ft.       5
₹ 8,571/sq.ft.       5
₹ 4,666/sq.ft.       5
₹ 5,556/sq.ft.       5
₹ 4,615/sq.ft.       5
₹ 7,641/sq.ft.       5
₹ 5,384/sq.ft.       5
₹ 14,242/sq.ft.      5
₹ 7,142/sq.ft.       5
₹ 10,714/sq.ft.      5
₹ 4,444/sq.ft.       5
₹ 5,600/sq.ft.       5
₹ 7,407/sq.ft.       5
₹ 6,500/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 16,000/sq.ft.      5
₹ 7,250/sq.ft.       4
₹ 9,822/sq.ft.       4
₹ 13,913/sq.ft.      4
₹ 5,660/sq.ft.       4
₹ 8,043/sq.ft.       4
₹ 8,500/sq.ft.       4
₹ 9,210/sq.ft.       4
₹ 15,000/sq.ft.      4
₹ 11,666/sq.ft.      4
₹ 8,432/sq.ft.       4
₹ 4,687/sq.ft.       4
₹ 10,416/sq.ft.      4
₹ 8,784/sq.ft.       4
₹ 16,666/sq.ft.      4
₹ 8,139/sq.ft.       4
₹ 8,108/sq.ft.       4
₹ 6,250/sq.ft.       4
₹ 7,496/sq.ft.       4
₹ 13,636/sq.ft.      4
₹ 8,474/sq.ft.       4
₹ 4,814/sq.ft.       4
₹ 8,484/sq.ft.       4
₹ 7,317/sq.ft.       4
₹ 8,445/sq.ft.       4
₹ 6,735/sq.ft.       4
₹ 8,358/sq.ft.       4
₹ 4,854/sq.ft.       4
₹ 15,384/sq.ft.      4
₹ 4,500/sq.ft.       4
₹ 8,787/sq.ft.       4
₹ 14,418/sq.ft.      4
₹ 10,383/sq.ft.      4
₹ 9,090/sq.ft.       4
₹ 8,163/sq.ft.       4
₹ 7,812/sq.ft.       4
₹ 7,272/sq.ft.       4
₹ 13,750/sq.ft.      4
₹ 16,470/sq.ft.      3
₹ 6,470/sq.ft.       3
₹ 11,363/sq.ft.      3
₹ 7,750/sq.ft.       3
₹ 6,593/sq.ft.       3
₹ 7,549/sq.ft.       3
₹ 9,473/sq.ft.       3
₹ 5,878/sq.ft.       3
₹ 6,476/sq.ft.       3
₹ 7,302/sq.ft.       3
₹ 9,615/sq.ft.       3
₹ 7,948/sq.ft.       3
₹ 8,606/sq.ft.       3
₹ 5,856/sq.ft.       3
₹ 11,000/sq.ft.      3
₹ 13,000/sq.ft.      3
₹ 7,056/sq.ft.       3
₹ 8,750/sq.ft.       3
₹ 6,542/sq.ft.       3
₹ 10,638/sq.ft.      3
₹ 8,400/sq.ft.       3
₹ 7,954/sq.ft.       3
₹ 6,644/sq.ft.       3
₹ 6,421/sq.ft.       3
₹ 7,400/sq.ft.       3
₹ 7,865/sq.ft.       3
₹ 9,011/sq.ft.       3
₹ 4,820/sq.ft.       3
₹ 8,532/sq.ft.       3
₹ 4,800/sq.ft.       3
₹ 6,921/sq.ft.       3
₹ 8,620/sq.ft.       3
₹ 8,886/sq.ft.       3
₹ 8,389/sq.ft.       3
₹ 8,450/sq.ft.       3
₹ 9,972/sq.ft.       3
₹ 6,667/sq.ft.       3
₹ 4,105/sq.ft.       3
₹ 5,319/sq.ft.       3
₹ 7,179/sq.ft.       3
₹ 13,392/sq.ft.      3
₹ 6,086/sq.ft.       3
₹ 5,397/sq.ft.       3
₹ 8,181/sq.ft.       3
₹ 9,900/sq.ft.       3
₹ 10,139/sq.ft.      3
₹ 13,870/sq.ft.      3
₹ 9,904/sq.ft.       3
₹ 14,430/sq.ft.      3
₹ 10,555/sq.ft.      3
₹ 10,204/sq.ft.      3
₹ 9,500/sq.ft.       3
₹ 8,222/sq.ft.       3
₹ 8,078/sq.ft.       3
₹ 6,404/sq.ft.       3
₹ 10,500/sq.ft.      3
₹ 5,325/sq.ft.       3
₹ 14,000/sq.ft.      3
₹ 7,150/sq.ft.       3
₹ 14,254/sq.ft.      3
₹ 8,080/sq.ft.       3
₹ 7,467/sq.ft.       3
₹ 8,148/sq.ft.       3
₹ 7,586/sq.ft.       3
₹ 8,604/sq.ft.       3
₹ 5,833/sq.ft.       3
₹ 5,735/sq.ft.       3
₹ 7,541/sq.ft.       3
₹ 6,387/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 7,083/sq.ft.       3
₹ 5,238/sq.ft.       3
₹ 4,513/sq.ft.       3
₹ 4,210/sq.ft.       3
₹ 16,969/sq.ft.      3
₹ 6,818/sq.ft.       3
₹ 8,215/sq.ft.       3
₹ 12,022/sq.ft.      2
₹ 13,270/sq.ft.      2
₹ 7,223/sq.ft.       2
₹ 8,834/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 9,128/sq.ft.       2
₹ 14,785/sq.ft.      2
₹ 19,767/sq.ft.      2
₹ 17,039/sq.ft.      2
₹ 11,765/sq.ft.      2
₹ 7,610/sq.ft.       2
₹ 5,839/sq.ft.       2
₹ 7,350/sq.ft.       2
₹ 9,743/sq.ft.       2
₹ 15,416/sq.ft.      2
₹ 8,846/sq.ft.       2
₹ 6,254/sq.ft.       2
₹ 13,343/sq.ft.      2
₹ 8,733/sq.ft.       2
₹ 9,922/sq.ft.       2
₹ 10,651/sq.ft.      2
₹ 9,797/sq.ft.       2
₹ 9,433/sq.ft.       2
₹ 9,672/sq.ft.       2
₹ 5,725/sq.ft.       2
₹ 15,500/sq.ft.      2
₹ 6,679/sq.ft.       2
₹ 10,545/sq.ft.      2
₹ 6,029/sq.ft.       2
₹ 9,007/sq.ft.       2
₹ 5,820/sq.ft.       2
₹ 7,908/sq.ft.       2
₹ 11,694/sq.ft.      2
₹ 5,150/sq.ft.       2
₹ 9,642/sq.ft.       2
₹ 6,647/sq.ft.       2
₹ 6,825/sq.ft.       2
₹ 6,141/sq.ft.       2
₹ 11,336/sq.ft.      2
₹ 5,588/sq.ft.       2
₹ 8,376/sq.ft.       2
₹ 15,551/sq.ft.      2
₹ 14,237/sq.ft.      2
₹ 13,108/sq.ft.      2
₹ 18,518/sq.ft.      2
₹ 6,428/sq.ft.       2
₹ 8,897/sq.ft.       2
₹ 5,100/sq.ft.       2
₹ 7,449/sq.ft.       2
₹ 5,517/sq.ft.       2
₹ 4,909/sq.ft.       2
₹ 6,422/sq.ft.       2
₹ 5,683/sq.ft.       2
₹ 8,947/sq.ft.       2
₹ 5,896/sq.ft.       2
₹ 16,985/sq.ft.      2
₹ 8,252/sq.ft.       2
₹ 18,271/sq.ft.      2
₹ 6,373/sq.ft.       2
₹ 5,674/sq.ft.       2
₹ 6,655/sq.ft.       2
₹ 9,025/sq.ft.       2
₹ 7,608/sq.ft.       2
₹ 10,699/sq.ft.      2
₹ 9,105/sq.ft.       2
₹ 7,878/sq.ft.       2
₹ 19,747/sq.ft.      2
₹ 6,313/sq.ft.       2
₹ 4,327/sq.ft.       2
₹ 5,513/sq.ft.       2
₹ 12,212/sq.ft.      2
₹ 15,263/sq.ft.      2
₹ 20,687/sq.ft.      2
₹ 8,433/sq.ft.       2
₹ 13,076/sq.ft.      2
₹ 6,987/sq.ft.       2
₹ 4,080/sq.ft.       2
₹ 5,056/sq.ft.       2
₹ 6,455/sq.ft.       2
₹ 4,856/sq.ft.       2
₹ 6,053/sq.ft.       2
₹ 6,315/sq.ft.       2
₹ 11,412/sq.ft.      2
₹ 6,333/sq.ft.       2
₹ 4,857/sq.ft.       2
₹ 8,100/sq.ft.       2
₹ 5,825/sq.ft.       2
₹ 3,911/sq.ft.       2
₹ 7,014/sq.ft.       2
₹ 8,519/sq.ft.       2
₹ 8,290/sq.ft.       2
₹ 10,596/sq.ft.      2
₹ 16,747/sq.ft.      2
₹ 12,222/sq.ft.      2
₹ 8,632/sq.ft.       2
₹ 5,808/sq.ft.       2
₹ 14,615/sq.ft.      2
₹ 10,237/sq.ft.      2
₹ 9,022/sq.ft.       2
₹ 7,185/sq.ft.       2
₹ 9,978/sq.ft.       2
₹ 16,858/sq.ft.      2
₹ 15,294/sq.ft.      2
₹ 8,166/sq.ft.       2
₹ 7,631/sq.ft.       2
₹ 11,726/sq.ft.      2
₹ 9,263/sq.ft.       2
₹ 6,189/sq.ft.       2
₹ 6,206/sq.ft.       2
₹ 6,190/sq.ft.       2
₹ 58/sq.ft.          2
₹ 6,927/sq.ft.       2
₹ 5,463/sq.ft.       2
₹ 10,370/sq.ft.      2
₹ 12,012/sq.ft.      2
₹ 3,695/sq.ft.       2
₹ 6,076/sq.ft.       2
₹ 4,745/sq.ft.       2
₹ 5,564/sq.ft.       2
₹ 4,307/sq.ft.       2
₹ 11,250/sq.ft.      2
₹ 7,863/sq.ft.       2
₹ 6,243/sq.ft.       2
₹ 7,758/sq.ft.       2
₹ 5,980/sq.ft.       2
₹ 5,828/sq.ft.       2
₹ 5,658/sq.ft.       2
₹ 8,518/sq.ft.       2
₹ 6,588/sq.ft.       2
₹ 11,992/sq.ft.      2
₹ 8,756/sq.ft.       2
₹ 9,482/sq.ft.       2
₹ 5,599/sq.ft.       2
₹ 4,000/sq.ft.       2
₹ 9,452/sq.ft.       2
₹ 8,517/sq.ft.       2
₹ 5,899/sq.ft.       2
₹ 6,217/sq.ft.       2
₹ 13,769/sq.ft.      2
₹ 8,609/sq.ft.       2
₹ 11,529/sq.ft.      2
₹ 8,524/sq.ft.       2
₹ 6,569/sq.ft.       2
₹ 9,600/sq.ft.       2
₹ 11,627/sq.ft.      2
₹ 7,574/sq.ft.       2
₹ 7,225/sq.ft.       2
₹ 6,318/sq.ft.       2
₹ 11,700/sq.ft.      2
₹ 8,720/sq.ft.       2
₹ 6,551/sq.ft.       2
₹ 9,677/sq.ft.       2
₹ 8,006/sq.ft.       2
₹ 7,530/sq.ft.       2
₹ 9,062/sq.ft.       2
₹ 8,972/sq.ft.       2
₹ 12,777/sq.ft.      2
₹ 6,985/sq.ft.       2
₹ 5,786/sq.ft.       2
₹ 11,333/sq.ft.      2
₹ 5,111/sq.ft.       2
₹ 9,259/sq.ft.       2
₹ 10,384/sq.ft.      2
₹ 8,310/sq.ft.       2
₹ 10,526/sq.ft.      2
₹ 6,686/sq.ft.       2
₹ 8,618/sq.ft.       2
₹ 8,582/sq.ft.       2
₹ 8,053/sq.ft.       2
₹ 9,449/sq.ft.       2
₹ 9,589/sq.ft.       2
₹ 8,305/sq.ft.       2
₹ 5,177/sq.ft.       2
₹ 5,671/sq.ft.       2
₹ 8,283/sq.ft.       2
₹ 8,411/sq.ft.       2
₹ 9,950/sq.ft.       2
₹ 10,553/sq.ft.      2
₹ 9,742/sq.ft.       2
₹ 9,791/sq.ft.       2
₹ 5,744/sq.ft.       2
₹ 8,294/sq.ft.       2
₹ 3,477/sq.ft.       2
₹ 8,814/sq.ft.       2
₹ 8,031/sq.ft.       2
₹ 9,550/sq.ft.       2
₹ 8,237/sq.ft.       2
₹ 6,049/sq.ft.       2
₹ 19,882/sq.ft.      2
₹ 5,929/sq.ft.       2
₹ 15,195/sq.ft.      2
₹ 10,489/sq.ft.      2
₹ 7,850/sq.ft.       2
₹ 12,444/sq.ft.      2
₹ 7,490/sq.ft.       2
₹ 6,692/sq.ft.       2
₹ 5,252/sq.ft.       2
₹ 13,928/sq.ft.      2
₹ 7,097/sq.ft.       2
₹ 7,817/sq.ft.       2
₹ 11,727/sq.ft.      2
₹ 9,565/sq.ft.       2
₹ 15,454/sq.ft.      2
₹ 6,571/sq.ft.       2
₹ 6,774/sq.ft.       2
₹ 9,620/sq.ft.       2
₹ 9,139/sq.ft.       2
₹ 9,074/sq.ft.       2
₹ 7,765/sq.ft.       2
₹ 14,303/sq.ft.      2
₹ 6,402/sq.ft.       2
₹ 8,159/sq.ft.       2
₹ 8,670/sq.ft.       2
₹ 8,024/sq.ft.       2
₹ 6,896/sq.ft.       2
₹ 8,974/sq.ft.       2
₹ 6,153/sq.ft.       2
₹ 9,306/sq.ft.       2
₹ 16,363/sq.ft.      2
₹ 13,709/sq.ft.      2
₹ 8,457/sq.ft.       2
₹ 5,454/sq.ft.       2
₹ 8,424/sq.ft.       2
₹ 7,987/sq.ft.       2
₹ 6,382/sq.ft.       2
₹ 14,683/sq.ft.      2
₹ 7,058/sq.ft.       2
₹ 5,982/sq.ft.       2
₹ 7,716/sq.ft.       2
₹ 4,761/sq.ft.       2
₹ 9,020/sq.ft.       2
₹ 6,938/sq.ft.       2
₹ 7,174/sq.ft.       2
₹ 11,715/sq.ft.      2
₹ 8,412/sq.ft.       2
₹ 8,835/sq.ft.       2
₹ 6,465/sq.ft.       2
₹ 6,839/sq.ft.       2
₹ 8,536/sq.ft.       2
₹ 19,000/sq.ft.      2
₹ 8,324/sq.ft.       2
₹ 14,285/sq.ft.      2
₹ 6,353/sq.ft.       2
₹ 6,406/sq.ft.       2
₹ 7,359/sq.ft.       2
₹ 7,751/sq.ft.       2
₹ 8,600/sq.ft.       2
₹ 10,666/sq.ft.      2
₹ 9,286/sq.ft.       2
₹ 5,797/sq.ft.       2
₹ 5,038/sq.ft.       2
₹ 10,531/sq.ft.      2
₹ 6,377/sq.ft.       2
₹ 6,429/sq.ft.       2
₹ 6,061/sq.ft.       2
₹ 6,325/sq.ft.       2
₹ 6,739/sq.ft.       2
₹ 7,200/sq.ft.       2
₹ 14,583/sq.ft.      2
₹ 6,983/sq.ft.       2
₹ 10,601/sq.ft.      2
₹ 7,585/sq.ft.       2
₹ 9,876/sq.ft.       2
₹ 9,909/sq.ft.       2
₹ 13,500/sq.ft.      2
₹ 5,882/sq.ft.       2
₹ 6,024/sq.ft.       2
₹ 11,724/sq.ft.      2
₹ 6,510/sq.ft.       2
₹ 41,245/sq.ft.      2
₹ 9,851/sq.ft.       2
₹ 8,075/sq.ft.       2
₹ 12,782/sq.ft.      2
₹ 9,182/sq.ft.       2
₹ 4,271/sq.ft.       2
₹ 18,181/sq.ft.      2
₹ 5,291/sq.ft.       2
₹ 6,597/sq.ft.       2
₹ 8,206/sq.ft.       2
₹ 17,619/sq.ft.      2
₹ 11,516/sq.ft.      2
₹ 16,960/sq.ft.      2
₹ 7,391/sq.ft.       2
₹ 10,603/sq.ft.      2
₹ 7,248/sq.ft.       2
₹ 14,214/sq.ft.      2
₹ 9,333/sq.ft.       2
₹ 14,257/sq.ft.      2
₹ 5,189/sq.ft.       2
₹ 15,998/sq.ft.      2
₹ 7,727/sq.ft.       2
₹ 18,000/sq.ft.      2
₹ 9,166/sq.ft.       2
₹ 8,504/sq.ft.       2
₹ 10,599/sq.ft.      2
₹ 6,812/sq.ft.       2
₹ 5,521/sq.ft.       2
₹ 7,857/sq.ft.       2
₹ 5,424/sq.ft.       2
₹ 14,545/sq.ft.      2
₹ 7,297/sq.ft.       2
₹ 7,846/sq.ft.       2
₹ 6,200/sq.ft.       2
₹ 15,151/sq.ft.      2
₹ 5,714/sq.ft.       2
₹ 6,950/sq.ft.       2
₹ 6,538/sq.ft.       2
₹ 9,135/sq.ft.       2
₹ 7,796/sq.ft.       2
₹ 10,476/sq.ft.      2
₹ 6,859/sq.ft.       2
₹ 13,333/sq.ft.      2
₹ 12,250/sq.ft.      2
₹ 6,722/sq.ft.       2
₹ 5,128/sq.ft.       2
₹ 6,338/sq.ft.       2
₹ 33,198/sq.ft.      2
₹ 8,035/sq.ft.       2
₹ 4,400/sq.ft.       2
₹ 5,470/sq.ft.       2
₹ 6,506/sq.ft.       2
₹ 7,627/sq.ft.       2
₹ 6,967/sq.ft.       2
₹ 7,780/sq.ft.       2
₹ 7,782/sq.ft.       2
₹ 6,111/sq.ft.       2
₹ 7,396/sq.ft.       2
₹ 9,146/sq.ft.       2
₹ 11,755/sq.ft.      2
₹ 5,405/sq.ft.       2
₹ 6,420/sq.ft.       2
₹ 9,027/sq.ft.       2
₹ 10,018/sq.ft.      2
₹ 6,178/sq.ft.       2
₹ 5,641/sq.ft.       2
₹ 8,611/sq.ft.       2
₹ 8,036/sq.ft.       2
₹ 8,072/sq.ft.       2
₹ 6,789/sq.ft.       2
₹ 7,884/sq.ft.       2
₹ 8,453/sq.ft.       2
₹ 6,134/sq.ft.       2
₹ 13,430/sq.ft.      2
₹ 8,410/sq.ft.       2
₹ 4,651/sq.ft.       2
₹ 13,383/sq.ft.      2
₹ 14,478/sq.ft.      2
₹ 10,516/sq.ft.      2
₹ 6,616/sq.ft.       2
₹ 16,608/sq.ft.      2
₹ 13,281/sq.ft.      2
₹ 6,209/sq.ft.       2
₹ 5,649/sq.ft.       2
₹ 5,614/sq.ft.       2
₹ 9,854/sq.ft.       2
₹ 13,224/sq.ft.      2
₹ 5,528/sq.ft.       2
₹ 7,825/sq.ft.       2
₹ 8,903/sq.ft.       2
₹ 5,284/sq.ft.       2
₹ 11,125/sq.ft.      2
₹ 21,538/sq.ft.      2
₹ 5,681/sq.ft.       2
₹ 11,505/sq.ft.      2
₹ 200,000/sq.ft.     2
₹ 11,028/sq.ft.      2
₹ 8,521/sq.ft.       2
₹ 13,991/sq.ft.      2
₹ 8,279/sq.ft.       2
₹ 10,936/sq.ft.      2
₹ 6,811/sq.ft.       2
₹ 6,702/sq.ft.       2
₹ 14,800/sq.ft.      2
₹ 7,945/sq.ft.       2
₹ 8,052/sq.ft.       1
₹ 8,557/sq.ft.       1
₹ 8,042/sq.ft.       1
₹ 10,375/sq.ft.      1
₹ 8,120/sq.ft.       1
₹ 7,951/sq.ft.       1
₹ 14,795/sq.ft.      1
₹ 8,347/sq.ft.       1
₹ 6,951/sq.ft.       1
₹ 6,601/sq.ft.       1
₹ 4,637/sq.ft.       1
₹ 9,218/sq.ft.       1
₹ 12,044/sq.ft.      1
₹ 17,691/sq.ft.      1
₹ 9,371/sq.ft.       1
₹ 10,491/sq.ft.      1
₹ 10,205/sq.ft.      1
₹ 10,283/sq.ft.      1
₹ 17,729/sq.ft.      1
₹ 5,759/sq.ft.       1
₹ 5,491/sq.ft.       1
₹ 13,989/sq.ft.      1
₹ 11,654/sq.ft.      1
₹ 11,346/sq.ft.      1
₹ 20,995/sq.ft.      1
₹ 19,943/sq.ft.      1
₹ 11,251/sq.ft.      1
₹ 8,123/sq.ft.       1
₹ 5,333/sq.ft.       1
₹ 4,603/sq.ft.       1
₹ 11,944/sq.ft.      1
₹ 13,480/sq.ft.      1
₹ 15,901/sq.ft.      1
₹ 8,622/sq.ft.       1
₹ 10,578/sq.ft.      1
₹ 11,061/sq.ft.      1
₹ 10,656/sq.ft.      1
₹ 7,360/sq.ft.       1
₹ 11,605/sq.ft.      1
₹ 5,257/sq.ft.       1
₹ 12,700/sq.ft.      1
₹ 11,989/sq.ft.      1
₹ 14,267/sq.ft.      1
₹ 7,714/sq.ft.       1
₹ 7,769/sq.ft.       1
₹ 8,297/sq.ft.       1
₹ 8,790/sq.ft.       1
₹ 4,923/sq.ft.       1
₹ 6,159/sq.ft.       1
₹ 9,734/sq.ft.       1
₹ 8,707/sq.ft.       1
₹ 6,998/sq.ft.       1
₹ 15,130/sq.ft.      1
₹ 7,654/sq.ft.       1
₹ 8,487/sq.ft.       1
₹ 6,064/sq.ft.       1
₹ 12,437/sq.ft.      1
₹ 6,032/sq.ft.       1
₹ 3,864/sq.ft.       1
₹ 8,737/sq.ft.       1
₹ 13,575/sq.ft.      1
₹ 6,914/sq.ft.       1
₹ 11,580/sq.ft.      1
₹ 7,079/sq.ft.       1
₹ 3,516/sq.ft.       1
₹ 5,076/sq.ft.       1
₹ 9,843/sq.ft.       1
₹ 4,657/sq.ft.       1
₹ 5,576/sq.ft.       1
₹ 5,910/sq.ft.       1
₹ 5,950/sq.ft.       1
₹ 6,778/sq.ft.       1
₹ 8,666/sq.ft.       1
₹ 17,548/sq.ft.      1
₹ 8,554/sq.ft.       1
₹ 6,550/sq.ft.       1
₹ 9,016/sq.ft.       1
₹ 2,051/sq.ft.       1
₹ 5,813/sq.ft.       1
₹ 10,309/sq.ft.      1
₹ 7,931/sq.ft.       1
₹ 7,679/sq.ft.       1
₹ 6,007/sq.ft.       1
₹ 18,688/sq.ft.      1
₹ 4,602/sq.ft.       1
₹ 4,345/sq.ft.       1
₹ 9,002/sq.ft.       1
₹ 20,666/sq.ft.      1
₹ 14,358/sq.ft.      1
₹ 9,696/sq.ft.       1
₹ 6,554/sq.ft.       1
₹ 17,543/sq.ft.      1
₹ 4,886/sq.ft.       1
₹ 6,168/sq.ft.       1
₹ 6,033/sq.ft.       1
₹ 3,713/sq.ft.       1
₹ 6,194/sq.ft.       1
₹ 9/sq.ft.           1
₹ 4,108/sq.ft.       1
₹ 10,754/sq.ft.      1
₹ 10,743/sq.ft.      1
₹ 17,378/sq.ft.      1
₹ 14,632/sq.ft.      1
₹ 4,792/sq.ft.       1
₹ 5,329/sq.ft.       1
₹ 5,407/sq.ft.       1
₹ 4,933/sq.ft.       1
₹ 7,068/sq.ft.       1
₹ 9,130/sq.ft.       1
₹ 591/sq.ft.         1
₹ 4,941/sq.ft.       1
₹ 7,893/sq.ft.       1
₹ 3,671/sq.ft.       1
₹ 10,627/sq.ft.      1
₹ 6,089/sq.ft.       1
₹ 8,367/sq.ft.       1
₹ 4,942/sq.ft.       1
₹ 5,904/sq.ft.       1
₹ 13,522/sq.ft.      1
₹ 15,124/sq.ft.      1
₹ 4,673/sq.ft.       1
₹ 6,485/sq.ft.       1
₹ 15,262/sq.ft.      1
₹ 5,739/sq.ft.       1
₹ 2,666/sq.ft.       1
₹ 6,137/sq.ft.       1
₹ 5,952/sq.ft.       1
₹ 6,562/sq.ft.       1
₹ 11,442/sq.ft.      1
₹ 5,965/sq.ft.       1
₹ 3,352/sq.ft.       1
₹ 4,600/sq.ft.       1
₹ 7,010/sq.ft.       1
₹ 6,842/sq.ft.       1
₹ 5,625/sq.ft.       1
₹ 7,920/sq.ft.       1
₹ 4,179/sq.ft.       1
₹ 11,600/sq.ft.      1
₹ 14,838/sq.ft.      1
₹ 13,177/sq.ft.      1
₹ 8,446/sq.ft.       1
₹ 6,870/sq.ft.       1
₹ 11,920/sq.ft.      1
₹ 6,552/sq.ft.       1
₹ 5,265/sq.ft.       1
₹ 7,891/sq.ft.       1
₹ 7,262/sq.ft.       1
₹ 16,445/sq.ft.      1
₹ 13,984/sq.ft.      1
₹ 15,982/sq.ft.      1
₹ 4,106/sq.ft.       1
₹ 8,982/sq.ft.       1
₹ 9,519/sq.ft.       1
₹ 8,734/sq.ft.       1
₹ 21,922/sq.ft.      1
₹ 8,700/sq.ft.       1
₹ 10,482/sq.ft.      1
₹ 5,413/sq.ft.       1
₹ 4,778/sq.ft.       1
₹ 9,856/sq.ft.       1
₹ 5,507/sq.ft.       1
₹ 7,453/sq.ft.       1
₹ 17,488/sq.ft.      1
₹ 8,802/sq.ft.       1
₹ 6,435/sq.ft.       1
₹ 7,872/sq.ft.       1
₹ 8,404/sq.ft.       1
₹ 22,700/sq.ft.      1
₹ 8,266/sq.ft.       1
₹ 7,760/sq.ft.       1
₹ 4,879/sq.ft.       1
₹ 7,547/sq.ft.       1
₹ 4,117/sq.ft.       1
₹ 11,209/sq.ft.      1
₹ 3,650/sq.ft.       1
₹ 3,664/sq.ft.       1
₹ 4,723/sq.ft.       1
₹ 12,009/sq.ft.      1
₹ 15,560/sq.ft.      1
₹ 4,861/sq.ft.       1
₹ 12,272/sq.ft.      1
₹ 4,818/sq.ft.       1
₹ 22,222/sq.ft.      1
₹ 4,700/sq.ft.       1
₹ 22,346/sq.ft.      1
₹ 5,296/sq.ft.       1
₹ 4,200/sq.ft.       1
₹ 10,306/sq.ft.      1
₹ 8,558/sq.ft.       1
₹ 8,124/sq.ft.       1
₹ 13,953/sq.ft.      1
₹ 14,658/sq.ft.      1
₹ 9,531/sq.ft.       1
₹ 9,912/sq.ft.       1
₹ 8,095/sq.ft.       1
₹ 6,077/sq.ft.       1
₹ 13,921/sq.ft.      1
₹ 8,823/sq.ft.       1
₹ 7,234/sq.ft.       1
₹ 10,418/sq.ft.      1
₹ 11,725/sq.ft.      1
₹ 4,404/sq.ft.       1
₹ 6,556/sq.ft.       1
₹ 6,587/sq.ft.       1
₹ 10,697/sq.ft.      1
₹ 8,387/sq.ft.       1
₹ 10,058/sq.ft.      1
₹ 7,882/sq.ft.       1
₹ 11,963/sq.ft.      1
₹ 7,402/sq.ft.       1
₹ 5,720/sq.ft.       1
₹ 6,768/sq.ft.       1
₹ 5,958/sq.ft.       1
₹ 11,497/sq.ft.      1
₹ 6,129/sq.ft.       1
₹ 11,559/sq.ft.      1
₹ 6,648/sq.ft.       1
₹ 6,361/sq.ft.       1
₹ 9,380/sq.ft.       1
₹ 9,076/sq.ft.       1
₹ 6,902/sq.ft.       1
₹ 5,541/sq.ft.       1
₹ 8,674/sq.ft.       1
₹ 13,425/sq.ft.      1
₹ 10,408/sq.ft.      1
₹ 10,257/sq.ft.      1
₹ 10,017/sq.ft.      1
₹ 10,888/sq.ft.      1
₹ 10,483/sq.ft.      1
₹ 7,779/sq.ft.       1
₹ 10,452/sq.ft.      1
₹ 9,984/sq.ft.       1
₹ 5,214/sq.ft.       1
₹ 11,869/sq.ft.      1
₹ 10,924/sq.ft.      1
₹ 6,900/sq.ft.       1
₹ 15,102/sq.ft.      1
₹ 6,319/sq.ft.       1
₹ 4,545/sq.ft.       1
₹ 3,500/sq.ft.       1
₹ 8,986/sq.ft.       1
₹ 9,370/sq.ft.       1
₹ 8,602/sq.ft.       1
₹ 9,264/sq.ft.       1
₹ 7,006/sq.ft.       1
₹ 17,271/sq.ft.      1
₹ 7,227/sq.ft.       1
₹ 7,066/sq.ft.       1
₹ 23,344/sq.ft.      1
₹ 6,493/sq.ft.       1
₹ 6,256/sq.ft.       1
₹ 16,230/sq.ft.      1
₹ 6,751/sq.ft.       1
₹ 6,176/sq.ft.       1
₹ 7,561/sq.ft.       1
₹ 11,538/sq.ft.      1
₹ 11,178/sq.ft.      1
₹ 4,807/sq.ft.       1
₹ 13,936/sq.ft.      1
₹ 11,854/sq.ft.      1
₹ 7,988/sq.ft.       1
₹ 10,094/sq.ft.      1
₹ 5,571/sq.ft.       1
₹ 13,513/sq.ft.      1
₹ 7,171/sq.ft.       1
₹ 4,037/sq.ft.       1
₹ 8,111/sq.ft.       1
₹ 9,664/sq.ft.       1
₹ 6,358/sq.ft.       1
₹ 9,125/sq.ft.       1
₹ 9,227/sq.ft.       1
₹ 15,360/sq.ft.      1
₹ 7,307/sq.ft.       1
₹ 6,389/sq.ft.       1
₹ 11,423/sq.ft.      1
₹ 11,386/sq.ft.      1
₹ 6,979/sq.ft.       1
₹ 11,923/sq.ft.      1
₹ 8,812/sq.ft.       1
₹ 10,723/sq.ft.      1
₹ 5,931/sq.ft.       1
₹ 7,103/sq.ft.       1
₹ 8,040/sq.ft.       1
₹ 4,868/sq.ft.       1
₹ 6,165/sq.ft.       1
₹ 10,773/sq.ft.      1
₹ 5,789/sq.ft.       1
₹ 4,931/sq.ft.       1
₹ 50,000/sq.ft.      1
₹ 13,296/sq.ft.      1
₹ 8,840/sq.ft.       1
₹ 8,856/sq.ft.       1
₹ 6,690/sq.ft.       1
₹ 6,761/sq.ft.       1
₹ 6,505/sq.ft.       1
₹ 6,969/sq.ft.       1
₹ 4,033/sq.ft.       1
₹ 5,443/sq.ft.       1
₹ 4,579/sq.ft.       1
₹ 4,869/sq.ft.       1
₹ 7,321/sq.ft.       1
₹ 6,894/sq.ft.       1
₹ 6,113/sq.ft.       1
₹ 6,083/sq.ft.       1
₹ 4,596/sq.ft.       1
₹ 5,367/sq.ft.       1
₹ 8,920/sq.ft.       1
₹ 8,907/sq.ft.       1
₹ 4,458/sq.ft.       1
₹ 11,190/sq.ft.      1
₹ 10,903/sq.ft.      1
₹ 9,459/sq.ft.       1
₹ 9,102/sq.ft.       1
₹ 9,701/sq.ft.       1
₹ 8,264/sq.ft.       1
₹ 4,456/sq.ft.       1
₹ 6,502/sq.ft.       1
₹ 4,786/sq.ft.       1
₹ 10,815/sq.ft.      1
₹ 8,522/sq.ft.       1
₹ 8,970/sq.ft.       1
₹ 6,022/sq.ft.       1
₹ 11,276/sq.ft.      1
₹ 6,618/sq.ft.       1
₹ 8,850/sq.ft.       1
₹ 10,004/sq.ft.      1
₹ 8,240/sq.ft.       1
₹ 9,846/sq.ft.       1
₹ 10,163/sq.ft.      1
₹ 11,741/sq.ft.      1
₹ 11,525/sq.ft.      1
₹ 5,432/sq.ft.       1
₹ 9,569/sq.ft.       1
₹ 6,926/sq.ft.       1
₹ 9,136/sq.ft.       1
₹ 9,310/sq.ft.       1
₹ 5,590/sq.ft.       1
₹ 4,587/sq.ft.       1
₹ 9,091/sq.ft.       1
₹ 6,201/sq.ft.       1
₹ 5,041/sq.ft.       1
₹ 8,298/sq.ft.       1
₹ 9,513/sq.ft.       1
₹ 10,134/sq.ft.      1

In [332]:
# Check for the unique types of sq_ft written in the price_sq_ft column.
df['price_per_sqft'].str.extract(r'/(.*)$')[0].value_counts()

0
sq.ft.    3004
Name: count, dtype: int64

In [333]:
# Extracting the only numerical value from the price_sq_ft column.
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace("₹", "").str.replace(",", "").str.strip().astype(float)

In [334]:
# Working on the bedroom columns, bathroom and balcony.
df.bedRoom.value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [335]:
# Since there are very less nan in the bedroom col and
# also apparently the same rows have so much nan in the othere columns as well and 
# hence only took the observations which has no nan.
df = df[~df['bedRoom'].isnull()]

In [336]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [337]:
df.bedRoom = df.bedRoom.str.split(" ").str.get(0).astype(int)

In [338]:
df.bathroom = df.bathroom.str.split(" ").str.get(0).astype(int)

In [339]:
# Working on the bedroom columns, bathroom and balcony.
df.balcony.value_counts()

balcony
3 Balconies     974
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [340]:
df.balcony = df.balcony.str.split(" ").str.get(0).str.replace("No", "0")

In [341]:
# Working on the bedroom columns, bathroom and balcony.
df.balcony.value_counts()

balcony
3     974
3+    862
2     749
1     315
0      97
Name: count, dtype: int64

In [342]:
# Working on the additional_rooms column and converting it into a multiclass column.
df.additionalRoom.value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Study Room,Pooja Room                              8
Servant Room,Study Room                            8
Study Room,Servant Room,Store Room                 7
Pooja Room,Store Room                              6
Pooja Room,Others                                  6
Others,Servant Room                                6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Servant Room,Others                     6
Study Room,Servant Room,Others                     5
Pooja Room,Store Room,Study Room,Servant Room      4
Pooja Room,Study Room,Store Room                   4
Servant Room,Pooja Room,Study Room,Store Room      3
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Study Room,Store Room                 2
Pooja Room,Study Room,Others                       2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Store Room,Pooja Room,Servant Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Pooja Room,Servant Room,Study Room,Store Room      1
Pooja Room,Study Room,Store Room,Servant Room      1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [343]:
# Check for the null values in the additional room column
df.additionalRoom.isnull().sum()

np.int64(1305)

In [344]:
df.additionalRoom.fillna('not_available', inplace = True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_6484\485969908.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.additionalRoom.fillna('not_available', inplace = True)

In [345]:
df.additionalRoom = df.additionalRoom.str.lower()

In [346]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not_available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not_available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not_available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [347]:
df.floorNum.str.split(" ").str.get(0).unique()

array(['4th\xa0\xa0', '1st\xa0\xa0', '12nd\xa0\xa0', '2nd\xa0\xa0',
       '5th\xa0\xa0', '3rd\xa0\xa0', '14th\xa0\xa0', '31st\xa0\xa0',
       '13rd\xa0\xa0', '25th\xa0\xa0', 'Ground', '11st\xa0\xa0',
       '10th\xa0\xa0', '20th\xa0\xa0', '8th\xa0\xa0', '21st\xa0\xa0',
       '6th\xa0\xa0', '9th\xa0\xa0', '18th\xa0\xa0', '29th\xa0\xa0',
       '7th\xa0\xa0', '15th\xa0\xa0', '32nd\xa0\xa0', '23rd\xa0\xa0',
       '43\xa0\xa0', 'Basement', '16th\xa0\xa0', '19th\xa0\xa0', nan,
       '17th\xa0\xa0', '30th\xa0\xa0', '28th\xa0\xa0', 'Lower',
       '27th\xa0\xa0', '33rd\xa0\xa0', '35th\xa0\xa0', '26th\xa0\xa0',
       '39th\xa0\xa0', '22nd\xa0\xa0', '24th\xa0\xa0', '38th\xa0\xa0',
       '45\xa0\xa0', '44\xa0\xa0', '34th\xa0\xa0', '40th\xa0\xa0'],
      dtype=object)

In [348]:
df.floorNum = df.floorNum.str.split(" ").str.get(0).str.replace("Ground", "0").str.replace("Basement", "-1").str.extract(r'(\d+)')

In [349]:
df.head(1)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not_available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [350]:
df.insert(loc = 4, column = 'area', value= round((df['price']*10000000)/df['price_per_sqft']))

In [351]:
df.insert(loc = 1, column = 'property_type', value = 'flat')

In [352]:
df.head(1)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not_available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [353]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2997 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2997 non-null   object
 1   property_type    2997 non-null   object
 2   society          2997 non-null   object
 3   price            2996 non-null   float64
 4   price_per_sqft   2996 non-null   float64
 5   area             2996 non-null   float64
 6   areaWithType     2997 non-null   object
 7   bedRoom          2997 non-null   int64
 8   bathroom         2997 non-null   int64
 9   balcony          2997 non-null   object
 10  additionalRoom   2997 non-null   object
 11  address          2991 non-null   object
 12  floorNum         2992 non-null   object
 13  facing           2123 non-null   object
 14  agePossession    2996 non-null   object
 15  nearbyLocations  2906 non-null   object
 16  description      2997 non-null   object
 17  furnishDetails   2200 non-null   object
 18  features         2590 non-null   object
 19  rating           2668 non-null   object
dtypes: float64(3), int64(2), object(15)
memory usage: 491.7+ KB

In [354]:
df.shape

(2997, 20)

In [355]:
df.to_csv("flats_basic_cleaned.csv", index = False)