In [30]:
import pandas as pd
import numpy as np

In [31]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

DATA_PATH_flats= PROJECT_ROOT / "Data" / "processed" / "flats_basic_cleaned.csv"
DATA_PATH_houses = PROJECT_ROOT / "Data" / "processed" / "houses_basic_cleaned.csv"

df_flats = pd.read_csv(DATA_PATH_flats)
df_houses = pd.read_csv(DATA_PATH_houses)

In [32]:
df = pd.concat([df_flats, df_houses], ignore_index=True)
df.reset_index(drop=True, inplace=True)

In [33]:
df.shape

(3961, 21)

In [34]:
df.shape

(3961, 21)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3391 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         2992 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
 20  noOfFloor        945 non-null    float64
dtypes: float64(5), int64(2), object(14)
memory usage: 650.0+ KB

In [36]:
df['floorNum'] = df['floorNum'].fillna(df['noOfFloor'])
df.drop(columns=['noOfFloor'], inplace=True)

In [37]:
df.head(50)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not_available,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not_available,"46b, Ashok Vihar, Gurgaon, Haryana",1.0,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not_available,"Sohna, Gurgaon, Haryana",12.0,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2.0,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5.0,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."
5,2 BHK Flat in Sector 36 Gurgaon,flat,signature global infinity mall,0.41,6269.0,654.0,Built Up area: 654 (60.76 sq.m.),2,2,3,not_available,"Sohna Sector 36, Sector 36 Gurgaon, Gurgaon, H...",3.0,NaN,undefined,NaN,Best in class property available at sector 36 ...,NaN,NaN,NaN
6,3 BHK Flat in Dwarka Expressway Gurgaon,flat,the cocoon,2.00,13333.0,1500.0,Super Built up area 1500(139.35 sq.m.),3,3,3,not_available,"Dwarka Expressway Gurgaon, Gurgaon, Haryana",5.0,NaN,0 to 1 Year Old,"['Shri Multispeciality Hospital', 'Esic Hospit...",Residential apartment for sell.The property co...,[],NaN,NaN
7,3 BHK Flat in Sector 104 Gurgaon,flat,ats triumph,1.80,7860.0,2290.0,Carpet area: 2290 (212.75 sq.m.),3,4,3,not_available,"Sector 104 Gurgaon, Gurgaon, Haryana",14.0,NaN,0 to 1 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...",Ats triumph is one of gurgaon's most sought af...,[],"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area4 out of 5', 'Amenities4.5 out of ..."
8,2 BHK Flat in Sector 88B Gurgaon,flat,vatika xpressions,1.10,8148.0,1350.0,Built Up area: 1350 (125.42 sq.m.)Carpet area:...,2,4,3+,study room,"H 23, Sector 88B Gurgaon, Gurgaon, Haryana",2.0,North-East,Under Construction,"['Dwarka Expressway', 'Adarsh public school,Ga...",We are the proud owners of this 2 bhk apartmen...,NaN,"['Feng Shui / Vaastu Compliant', 'Intercom Fac...",NaN
9,3 BHK Flat in Sector 78 Gurgaon,flat,raheja revanta,4.75,16885.0,2813.0,Built Up area: 2813 (261.34 sq.m.),3,3,2,servant room,"Sector 78 Gurgaon, Gurgaon, Haryana",31.0,NaN,Dec-23,"['Sapphire 83 Mall', 'NH-8', 'Bal Bharti Publi...","This 3 bhk flat is located in raheja revanta, ...",NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
10,2 BHK Flat in Sector 81 Gurgaon,flat,signature global city 81,0.96,9767.0,983.0,Carpet area: 1075 (99.87 sq.m.),2,2,2,not_available,"Sector 81 Gurgaon, Gurgaon, Haryana",1.0,NaN,Jun-24,"['Ambience Mall New', 'Dwarka Expressway', 'NH...",Signature global city 81 is one of gurgaon's m...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4.5 out of 5', 'Safety4.5 out of ..."
11,2 BHK Flat in Sohna,flat,hcbs sports ville,0.29,5587.0,519.0,Carpet area: 519 (48.22 sq.m.),2,2,1,not_available,"Sohna, Gurgaon, Haryana",4.0,NaN,1 to 5 Year Old,"['The roadside cafe', 'GD Goenka Mess', 'ROyal...",Affordable housing in gurgaon and surrounded b...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Green Area4 out of 5', 'Amenities4 out of 5'..."
12,3 BHK Flat in Sector 79 Gurgaon,flat,supertech araville,1.35,6940.0,1945.0,Carpet area: 1945 (180.7 sq.m.),3,3,3,not_available,"Sector 79 Gurgaon, Gurgaon, Haryana",4.0,NaN,1 to 5 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Well spacious, nicely built with wooden floori...","['1 Water Purifier', '2 Fan', '1 Geyser', '3 L...",NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
13,2 BHK Flat in Sector 33 Gurgaon,flat,godrej,0.95,6859.0,1385.0,Super Built up area 1385(128.67 sq.m.),2,2,3+,not_available,"Flat No. :- 301, Sector 33 Gurgaon, Gurgaon, H...",3.0,South-East,Under Construction,NaN,Its an godrej project nature plus.\nOn 3rd flo...,NaN,NaN,"['Environment3 out of 5', 'Safety4 out of 5', ..."
14,2 BHK Flat in Sector 90 Gurgaon,flat,shree vardhman flora,0.70,5384.0,1300.0,Super Built up area 1300(120.77 sq.m.),2,2,3,study room,"Sector 90 Gurgaon, Gurgaon, Haryana",13.0,NaN,0 to 1 Year Old,"['IRIS Broadway Mall', 'Dwarka Expressway', 'S...",This 2 bhk apartment is available for sale in ...,NaN,"['Intercom Facility', 'Lift(s)', 'Park']","['Green Area5 out of 5', 'Amenities5 out of 5'..."
15,4 BHK Flat in Sector 108 Gurgaon,flat,sobha city,3.95,16859.0,2343.0,Built Up area: 2343 (217.67 sq.m.)Carpet area:...,4,5,3,not_available,"Sector 108, Sector 108 Gurgaon, Gurgaon, Haryana",25.0,NaN,undefined,"['Dwarka Sector 21', 'Dwarka Expressway', 'Vas...",This is sale property............................,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4.5 out of 5'..."
16,1 BHK Flat in Sector 62 Gurgaon,flat,senate court,0.90,14084.0,639.0,Built Up area: 639 (59.37 sq.m.),1,1,0,not_available,"Senate Court, Sector 62, Gurgaon, Sector 62 Gu...",0.0,NaN,undefined,"['Radhakrishna Shani Mandir', 'Sanatan Dharm M...",Looking for a 1 bhk apartment for sale in gurg...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
17,2 BHK Flat in Sector 102 Gurgaon,flat,shapoorji pallonji joyville gurugram,1.05,11475.0,915.0,Carpet area: 915 (85.01 sq.m.),2,2,2,not_available,"G04, Sector 102 Gurgaon, Gurgaon, Haryana",0.0,NaN,Mar-24,"['Khan Market', 'The Esplanade Mall', 'Dwarka ...",New upcoming available in next 6-9 months,[],"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Amenities5 out of 5'..."
18,2 BHK Flat in Sector 93 Gurgaon,flat,signature global orchard avenue 2,NaN,NaN,NaN,Carpet area: 577.11 (53.62 sq.m.),2,2,3,not_available,"L-1104, Sector 93 Gurgaon, Gurgaon, Haryana",11.0,East,Under Construction,"['Huda Metro Station', 'V3S Sapphire Ninety', ...",Looking for a budget-Friendly 2 bhk flat in a ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
19,3 BHK Flat in Sector-33 Sohna,flat,central park flower valley,2.20,10476.0,2100.0,Super Built up area 2100(195.1 sq.m.),3,3,3,servant room,"Sector-33 Sohna, Gurgaon, Haryana",12.0,North-East,0 to 1 Year Old,"['Airia Mall', 'NH 248A', 'NE 4, Haryana', 'GD...","This beautiful 3 bhk flat in sector-33 sohna, ...","['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
20,2 BHK Flat in Sector 89 Gurgaon,flat,smart world gems,1.01,9156.0,1103.0,Carpet area: 1103 (102.47 sq.m.),2,2,2,study room,"Sector 89 Gurgaon, Gurgaon, Haryana",4.0,NaN,Dec-25,"['Sant Soordas Sihi Metro Station', 'Airia Mal...",Possession soon . Luxurious flat with terrace ...,NaN,"['Intercom Facility', 'Lift(s)', 'Swimming Poo...","['Environment4 out of 5', 'Safety4 out of 5', ..."
21,3 BHK Flat in Sector 79 Gurgaon,flat,bestech altura,1.85,8604.0,2150.0,Super Built up area 2150(199.74 sq.m.),3,4,3+,servant room,"Sector 79 Gurgaon, Gurgaon, Haryana",11.0,North,0 to 1 Year Old,"['Sapphire 83 Mall', 'NH -8', 'Golf Course Ext...",This lovely 3 bhk apartment/flat in sector 79 ...,"['5 AC', '1 Chimney', '1 Modular Kitchen', 'No...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
22,2 BHK Flat in Sector 89 Gurgaon,flat,smart world gems,0.86,7796.0,1103.0,Super Built up area 1103(102.47 sq.m.),2,3,3,not_available,"Sector 89 Gurgaon, Gurgaon, Haryana",4.0,NaN,By 2023,"['Sant Soordas Sihi Metro Station', 'Airia Mal...",We are the proud owners of this 2 bhk apartmen...,[],NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
23,3 BHK Flat in Sector 102 Gurgaon,flat,emaar imperial gardens,1.85,9135.0,2025.0,Carpet area: 2025 (188.13 sq.m.),3,3,3+,servant room,"Sector 102 Gurgaon, Gurgaon, Haryana",0.0,South-West,1 to 5 Year Old,"['Satya The Hive Mall', 'Gurugram Road', 'Dwar...",Private garden area well maintained\nNo hassle...,"['5 Wardrobe', '8 Fan', '1 Exhaust Fan', '20 L...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Amenities5 out of 5'..."
24,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,2.85,12855.0,2217.0,Super Built up area 2217(205.97 sq.m.),3,3,3+,servant room,"Sector 113 Gurgaon , Gurgaon, Haryana",10.0,East,0 to 1 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",La vida by tata housing is one of the most pop...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
25,2 BHK Flat in Sector 36 Gurgaon,flat,the serenas,0.42,7910.0,531.0,Carpet area: 531 (49.33 sq.m.),2,2,1,not_available,"Sohna Sector 36, Sector 36 Gurgaon, Gurgaon, H...",3.0,NaN,undefined,NaN,Best in class property available at sector 36 ...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,NaN
26,3 BHK Flat in Sector 65 Gurgaon,flat,m3m golfestate,6.15,18331.0,3355.0,Built Up area: 3355 (311.69 sq.m.)Carpet area:...,3,4,2,not_available,"Sector 65, Sector 65 Gurgaon, Gurgaon, Haryana",20.0,North-East,undefined,"['Sector 54 Chowk Metro Station', 'Sahara Mall...",One of the best units in m3m golf estate with ...,NaN,NaN,"['Green Area5 out of 5', 'Amenities5 out of 5'..."
27,3 BHK Flat in Sector 48 Gurgaon,flat,central park resort belgravia residences,6.25,24300.0,2572.0,Carpet area: 2880 (267.56 sq.m.),3,5,3+,servant room,"Sector 48 Gurgaon, Gurgaon, Haryana",5.0,South-East,5 to 10 Year Old,"['Decathlon Sohna Road', 'Raheja Mall', 'Eleme...","Situated in sector 48 gurgaon, central park re...","['6 Fan', '1 Exhaust Fan', '4 Geyser', '55 Lig...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
28,2 BHK Flat in Sector 37C Gurgaon,flat,apex builders,0.42,5600.0,750.0,Carpet area: 750 (69.68 sq.m.),2,2,2,not_available,"Sector 37C Gurgaon, Gurgaon, Haryana",4.0,North,1 to 5 Year Old,"['Kamla Hospital Gurgaon', 'Shri Multispeciali...",Have car parking available and connected to ne...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Safety4 out of 5', ..."
29,2 BHK Flat in Sector 3 Gurgaon,flat,godrej habitat,1.35,12784.0,1056.0,Built Up area: 1056 (98.11 sq.m.)Carpet area: ...,2,2,0,not_available,"Godrej Habitat, Sector-3, Gurgaon, Sector 3 Gu...",4.0,North-East,undefined,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Self owning property , shifting out of country...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4.5 out of 5', 'Safety4.5 out of ..."
30,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not_available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
31,4 BHK Flat in Sector 43 Gurgaon,flat,bhawna cghs,3.25,10156.0,3200.0,Super Built up area 3200(297.29 sq.m.)Carpet a...,4,4,3+,pooja room,"Sector 43 Gurgaon, Gurgaon, Haryana",12.0,NaN,5 to 10 Year Old,"['Sector 42-43 metro station', 'Sector 53-54 m...",4 bhk + pooja room- Huge spacious rooms and ha...,"['7 Fan', '11 Light', '7 AC', '1 Modular Kitch...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Safety4 out of 5', ..."
32,2 BHK Flat in Sector 88A Gurgaon,flat,adani aangan arcade,0.45,7194.0,626.0,Carpet area: 625.47 (58.11 sq.m.),2,2,1,not_available,"Tower A-4, Flat No. 804, Sector 88A Gurgaon, G...",8.0,NaN,0 to 1 Year Old,"['Reliance Trends Newtown Square Mall', 'Patau...",This is 2bhk flat at 8th floor of tower a-4. \...,"['1 Modular Kitchen', '2 Wardrobe', 'No AC', '...","['Lift(s)', 'Maintenance Staff', 'Park']",NaN
33,3 BHK Flat in Sector 92 Gurgaon,flat,sare green parc,0.85,6538.0,1300.0,Built Up area: 1300 (120.77 sq.m.),3,2,2,not_available,"Sector 92, Sector 92 Gurgaon, Gurgaon, Haryana",20.0,NaN,undefined,"['Huda city centre metro station', 'Iffco chow...",Best in class property available at sector 92 ...,NaN,NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."
34,2 BHK Flat in Sector 90 Gurgaon,flat,shree vardhman flora,0.75,5769.0,1300.0,Carpet area: 1300 (120.77 sq.m.),2,2,3,not_available,"Sector 90, Sector 90 Gurgaon, Gurgaon, Haryana",8.0,North-East,undefined,"['IRIS Broadway Mall', 'Dwarka Expressway', 'S...",Best in class property available at sector 90 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area5 out of 5', 'Amenities5 out of 5'..."
35,2 BHK Flat in Sector 68 Gurgaon,flat,supertech hues,0.82,6950.0,1180.0,Super Built up area 1180(109.63 sq.m.),2,2,3+,others,"Sector-68 Gurgaon, Sector 68 Gurgaon, Gurgaon,...",21.0,NaN,Under Construction,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Residential apartment for sell.The property co...,NaN,"['Intercom Facility', 'Lift(s)', 'Feng Shui / ...","['Environment4 out of 5', 'Safety5 out of 5', ..."
36,3 BHK Flat in Sector 109 Gurgaon,flat,chintels paradiso,1.80,8866.0,2030.0,Super Built up area 2030(188.59 sq.m.)Carpet a...,3,3,2,servant room,"Sector 109 Gurgaon, Gurgaon, Haryana",0.0,East,5 to 10 Year Old,"['Gyaananda School', 'The NorthCap University'...",Greenery both sides of balconies \nOne side ch...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Amenities5 out of 5'..."
37,2 BHK Flat in Sohna,flat,breez global hill view,0.30,5403.0,555.0,Super Built up area 655(60.85 sq.m.)Carpet are...,2,2,2,not_available,"T 3, Sohna, Gurgaon, Haryana",6.0,North-East,0 to 1 Year Old,"['Huda City Centre', 'Omaxe City Centre', 'Nin...",Low density project already 300 family residin...,"['1 Fan', '1 Light', 'No AC', 'No Bed', 'No Ch...","['Security / Fire Alarm', 'Private Garden / Te...","['Environment4 out of 5', 'Safety4 out of 5', ..."
38,2 BHK Flat in Sector 37C Gurgaon,flat,ild greens,0.78,5714.0,1365.0,Super Built up area 1365(126.81 sq.m.)Built Up...,2,2,3,not_available,"101, Tower-7, Sector 37C Gurgaon, Gurgaon, Har...",1.0,North,5 to 10 Year Old,"['The Esplanade Mall', 'Gurgaon Road', 'Delhi ...","Rooms are well ventilated and airy, good open ...","['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Amenities4.5 out of ..."
39,3 BHK Flat in Sector 43 Gurgaon,flat,ansal sushant lok ci,2.00,15151.0,1320.0,Carpet area: 1320 (122.63 sq.m.),3,3,2,servant room,"C 488,1 St Floor, Sector 43 Gurgaon, Gurgaon, ...",1.0,North,10+ Year Old,"['Huda city centre metro station', 'Sector 42-...","Its huge inside,the bebrooms are quote spaciou...","['3 Bed', '5 Wardrobe', '6 Fan', '1 Sofa', '1 ...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
40,2 BHK Flat in Sohna,flat,ashiana mulberry,0.74,6200.0,1194.0,Carpet area: 1210 (112.41 sq.m.),2,2,3+,not_available,"Sohna, Gurgaon, Haryana",12.0,North-West,0 to 1 Year Old,"['Discount Department Store', 'Badshahpur Sohn...",Available with fully furnished kitchen and mas...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
41,3 BHK Flat in Sector 106 Gurgaon,flat,godrej meridien,3.20,16000.0,2000.0,Carpet area: 2002 (185.99 sq.m.),3,3,3+,servant room,"609, Sector 106 Gurgaon, Gurgaon, Haryana",6.0,NaN,Sep-25,"['Huda metro station', 'Gurgaon Dreamz Mall', ...",It's a clubhouse facing inventory and directly...,[],"['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
42,4 BHK Flat in Sector 82 Gurgaon,flat,mapsko casa bella,1.30,6378.0,2038.0,Super Built up area 1960(182.09 sq.m.),4,4,3+,servant room,"Sector 82 Gurgaon, Gurgaon, Haryana",1.0,North,1 to 5 Year Old,"['Vatika City Centre Mall', 'Pataudi Road', 'B...","Spacious, completely filled society, on main r...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Amenities4 out of ..."
43,2 BHK Flat in Ashok Vihar Phase 3 Extension,flat,pooja apartment,0.25,3571.0,700.0,Carpet area: 700 (65.03 sq.m.),2,2,2,not_available,"Flat No 201, Ashok Vihar Phase 3 Extension, Gu...",2.0,East,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",2nd floor with car parking at ground level. In...,"['2 Fan', '2 Geyser', '6 Light', '1 Chimney', ...",NaN,"['Environment3 out of 5', 'Safety4 out of 5', ..."
44,3 BHK Flat in Sohna,flat,signature global park,0.95,7846.0,1211.0,Built Up area: 1210.73 (112.48 sq.m.)Carpet ar...,3,2,3+,not_available,"Sohna, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Low rise building, all amenities are available...",[],"['Security / Fire Alarm', 'Lift(s)', 'Swimming...","['Green Area5 out of 5', 'Amenities5 out of 5'..."
45,4 BHK Flat in Sector 90 Gurgaon,flat,dlf new town heights,1.99,7297.0,2727.0,Carpet area: 2727 (253.35 sq.m.),4,4,3+,"pooja room,servant room","Sector 90 Gurgaon, Gurgaon, Haryana",9.0,East,1 to 5 Year Old,"['Manish Gallexie 91', 'NH-8 IMT Manesar', 'RH...",4 bhk flat is located in dlf new town heights ...,"['8 Fan', '1 Exhaust Fan', '6 Geyser', '1 Stov...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Amenities5 out of 5'..."
46,2 BHK Flat in Sector 106 Gurgaon,flat,paras dews,1.05,7581.0,1385.0,Carpet area: 1385 (128.67 sq.m.),2,2,2,not_available,"Sector 106 Gurgaon, Gurgaon, Haryana",5.0,West,0 to 1 Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...",It's on main dwarka expressway. Very close to ...,"['3 Fan', '2 Geyser', '7 Light', '3 AC', 'No B...","['Security / Fire Alarm', 'Power Back-up', 'In...",NaN
47,3 BHK Flat in Sector 85 Gurgaon,flat,godrej air,1.83,10005.0,1829.0,Carpet area: 1829 (169.92 sq.m.),3,3,3+,not_available,"Sector 85 Gurgaon, Gurgaon, Haryana",18.0,NaN,Mar-24,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",Godrej air is one of gurgaon's most sought aft...,"['1 Exhaust Fan', '1 Modular Kitchen', 'No AC'...","['Security / Fire Alarm', 'Lift(s)', 'Centrall...","['Environment5 out of 5', 'Safety4.5 out of 5'..."
48,3 BHK Flat in Sector 82A Gurgaon,flat,dlf the primus,2.25,10714.0,2100.0,Carpet area: 2100 (195.1 sq.m.),3,3,3+,servant room,"Sector 82A Gurgaon, Gurgaon, Haryana",29.0,East,1 to 5 Year Old,"['Sapphire 83', 'NH 48', 'Cambridge Montessori...",Located in the popular residential address of ...,"['1 Water Purifier', '7 Fan', '1 Fridge', '1 E...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Amenities5 out of 5'..."

In [38]:
df.insert(loc = 3, column = 'sector', value = df['property_name'].str.split("in").str.get(1).str.replace("Gurgaon", "").str.strip())

In [39]:
df.sector = df.sector.str.lower()

In [40]:

df.sector.unique()

array(['krishna colony', 'ashok vihar', 'sohna', 'sector 61', 'sector 92',
       'sector 36', 'dwarka expressway', 'sector 104', 'sector 88b',
       'sector 78', 'sector 81', 'sector 79', 'sector 33', 'sector 90',
       'sector 108', 'sector 62', 'sector 102', 'sector 93',
       'sector-33 sohna', 'sector 89', 'sector 113', 'sector 65',
       'sector 48', 'sector 37c', 'sector 3', 'new palam vihar',
       'sector 43', 'sector 88a', 'sector 68', 'sector 109', 'sector 106',
       'sector 82', 'ashok vihar phase 3 extension', 'sector 85',
       'sector 82a', 'dlf phase 4', 'sector 10a', 'sector 1a imt manesar',
       'block a surya vihar', 'sector 84', 'sector 71', 'sector-7 hous',
       'sector 77', 'sector 37d', 'sector 67a', 'sector 57', 'sector 95',
       'sector 99a', 'sector 103', 'sector 49', 'sector 30', 'sector 86',
       'sector 66', 'sector 15 part 1', 'laxman vihar', 'sector 22',
       'sector 63a', 'sector 95a', 'sector 52', 'sector 67',
       'sushant lok phase 1', 'sector 107', 'sector 12a', 'sohna road',
       'ashok vihar phase 2', 'rajiv colony', 'sector 2', 'garauli kalan',
       'bhawani enclave', 'sector 99', 'iffco chowk', 'palam vihar',
       'sector 91', 'near sector 1 market', 'sector 70', 'sector 70a',
       'gwal pahari', 'sector 7', 'malibu town', 'golf course road',
       'sector 4', 'sector 54', 'sector 111', 'chakkarpur', 'sector 41',
       'sector 12', 'sector 73', 'sector 36 sohna', 'sector 56',
       'sector 83', 'sector 53', 'sector 72', 'sector 1 imt manesar',
       'sector 69', 'sector 47', 'sector 63', 'sector 110', 'kanahi',
       'sector-11 sohna', 'dlf phase 5', 'sector 9a', 'sector 28',
       'sector 14', 'nirvana country', 'dlf phase 2', 'sector 59',
       'dlf phase 3', 'heritage city', 'sector 1', 'sector 38',
       'sector 15', 'ambience island', 'sector 112', 'sector 45',
       'sector 74', 'sector 60', 'sector 51', 'sector 50', 'suncity',
       'sector 110 a', 'sector 39', 'sai kunj', 'manesar', 'sector 58',
       'imt manesar', 'sector 80', 'mg road', 'sector 55', 'sultanpur',
       'sector 23a', 'sector 36a', 'civil l', 'sector 76',
       'new colony, sector 7', 'sector 31', 'lajpat nagar', 'sector 89 a',
       'new', 'sector 11', 'sector 32', 'surya vihar',
       'near pataudi chowk', 'cyber city', 'new colony', 'subhash nagar',
       'ats marigold', 'sector-2 sohna', 'adarsh nagar', 'sector 37a',
       'sushant lok phase 3', 'carterpuri village', 'valley view estate',
       'shanti nagar', 'sushant lok', 'mehrauli  road',
       'laxman vihar phase 2', 'sector-5 sohna', 'faridabad road',
       'sector 5 chowk', 'old delhi road, opp sector-14', 'sector 21',
       'sector 5', 'dayanand colony', 'samaspur',
       'nirvana country pocket h', 'patel nagar', 'surat nagar 1',
       'sispal vihar', 'golf course ext road', 'shankar vihar',
       'new palam vihar phase 2', 'sector 24', 'sector-35 sohna',
       'bhondsi', 'palam vihar extension', 'saroop garden rajendra park',
       'sector 4 urban estate', 'bptp', 'sector 105', 'south city 1',
       'sector 9', 'sector 40', 'dharam colony', 'rajendra park',
       'godrej aria , sector 79 ,', 'sector 21a faridabad', 'dlf phase 1',
       'b block sushant lok phase 1', 'new palam vihar phase 1',
       'uppals southend', 'hsiidc plot sector 1 imt manesar',
       'sector 15 part 2', 'nars', 'c block sushant lok phase 1',
       'greenwood city', 'sector 23', 'sector 17c', 'shivaji nagar',
       'hira nagar', 'gopal nagar, garhi ghasita, sonipat',
       'jat colony,fazilpur/taj nagar road', 'sector 17a', 'kheri',
       'madanpuri', 'mohan nagar', 'daulatabad', 'vishnu garden',
       'new basti', 'sector 8', 'maruti kunj', 'laxmi garden',
       'sector 9b', 'saraswati vihar', 'bhora kalan',
       'near nand hospital', 'shivpuri', 'jyoti park',
       'surat nagar phase 2', 'rajiv nagar', 'arjun nagar',
       'ashok vihar phase i', 'block h ashok vihar phase iii extension',
       'devilal colony', 'prem nagar', 'bhim nagar', 'surat nagar',
       'gandhi nagar', 'khandsa', 'ravi nagar', 'urban estate, sector 5',
       'west rajiv nagar', 'near khandsa road', 'sheetla colony',
       'farukhnagar', 'mianwali colony', 'part 3 sector 5', 'lucknow',
       'pataudi road', 'shakti nagar', 'baldev nagar', 'acharya puri',
       'garhi harsaru', 'pratap nagar', 'manohar nagar', 'vir nagar',
       'hno 13 sagar enclave sura', 'sector 13', 'ram nagar',
       'block g sector-57', 'sector 17', 'sector 6', 'sector 3a',
       'om nagar', 'anand garden, sector-105', 'jacobpura',
       'tekchand nagar', 'ashok vihar phase 3', "ansal's palam vihar",
       'jacobpura near sadar bazar', 'shivji park colony',
       'udyog vihar phase 1', 'mahalaxmi garden, rajendra place',
       'rattan garden', 'sadar bazar', 'naharpur rupa',
       'laxman vihar, railway road,', 'sector-5 sheetla colony', 'damdma',
       ', delhi ncr', 'new jyoti park', 'sohna  road', 'mahavir pura',
       'sector 37b', 'g block dlf city phase 1', 'park view',
       'ravi nager basai road', 'begampur khatola', 'dhankot',
       'rajiv chowk',
       'devi lal colony gali no 12 gurgaon nr omkar public school',
       'alipur', 'saraswati enclave',
       'sec 3 bhim vihar part 1 bhimgher kheri', 'near euro',
       'bhimgarh kheri phase 3', 'huda saraswati vihar',
       'laxmna vihar, phase 2', 'sector 17b', 'sector 46',
       'sushant lok phase 2', 'ansal plaza',
       'a block sushant lok phase 1', 'sector 27', 'b1 block sector 57',
       'mayfield garden', 'sector 42', 'sector 26', 'south city',
       'rosewood', 'v block dlf phase 3', 'bissar'], dtype=object)

In [41]:
sector_map = {
    'krishna colony': 'sector 7',
    'ashok vihar': 'sector 5',
    'sohna': 'sector 48',
    'dwarka expressway': 'sector 102',
    'new palam vihar': 'sector 1',
    'ashok vihar phase 3 extension': 'sector 5',
    'dlf phase 4': 'sector 28',
    'block a surya vihar': 'sector 21',
    'sector-7 hous': 'sector 7',
    'sushant lok phase 1': 'sector 43',
    'sohna road': 'sector 48',
    'ashok vihar phase 2': 'sector 5',
    'rajiv colony': 'sector 12A',
    'garauli kalan': 'sector 9',
    'bhawani enclave': 'sector 9B',
    'iffco chowk': 'sector 18',
    'palam vihar': 'sector 1',
    'near sector 1 market': 'sector 1',
    'gwal pahari': 'sector 61',
    'malibu town': 'sector 47',
    'golf course road': 'sector 53',
    'kanahi': 'sector 45',
    'dlf phase 5': 'sector 43',
    'nirvana country': 'sector 50',
    'dlf phase 2': 'sector 25',
    'heritage city': 'sector 62',
    'ambience island': 'sector 24',
    'suncity': 'sector 54',
    'sai kunj': 'sector 47',
    'manesar': 'sector 1A IMT Manesar',
    'imt manesar': 'sector 1A IMT Manesar',
    'mg road': 'sector 28',
    'sultanpur': 'sector 56',
    'civil l': 'sector 15',
    'new colony, sector 7': 'sector 7',
    'lajpat nagar': 'sector 14',
    'new': 'sector unknown',
    'surya vihar': 'sector 21',
    'near pataudi chowk': 'sector 10',
    'cyber city': 'sector 24',
    'new colony': 'sector 7',
    'subhash nagar': 'sector 12',
    'ats marigold': 'sector 89',
    'adarsh nagar': 'sector 7',
    'sushant lok phase 3': 'sector 57',
    'carterpuri village': 'sector 23A',
    'valley view estate': 'sector 57',
    'shanti nagar': 'sector 11',
    'sushant lok': 'sector 43',
    'mehrauli road': 'sector 14',
    'faridabad road': 'sector 58',
    'sector 5 chowk': 'sector 5',
    'old delhi road, opp sector-14': 'sector 14',
    'dayananad colony': 'sector 6',
    'samaspur': 'sector 59',
    'nirvana country pocket h': 'sector 50',
    'patel nagar': 'sector 14',
    'surat nagar 1': 'sector 104',
    'sispal vihar': 'sector 49',
    'golf course ext road': 'sector 58',
    'shankar vihar': 'sector 28',
    'bhondsi': 'sector 76',
    'palam vihar extension': 'sector 1',
    'saroop garden rajendra park': 'sector 15',
    'bptp': 'sector 66',
    'south city 1': 'sector 40',
    'dharam colony': 'sector 23A',
    'rajendra park': 'sector 8',
    'dlf phase 1': 'sector 26',
    'new palam vihar phase 1': 'sector 2',
    'uppals southend': 'sector 49',
    'nars': 'sector unknown',
    'greenwood city': 'sector 45',
    'shivaji nagar': 'sector 11',
    'hira nagar': 'sector 7',
    'gopal nagar, garhi ghasita, sonipat': 'not gurgaon',
    'jat colony,fazilpur/taj nagar road': 'sector 49',
    'kheri': 'sector 5',
    'madanpuri': 'sector 7',
    'mohan nagar': 'sector 6',
    'daulatabad': 'sector 4',
    'vishnu garden': 'sector 5',
    'new basti': 'sector 7',
    'maruti kunj': 'sector 107',
    'laxmi garden': 'sector 7',
    'saraswati vihar': 'sector 28',
    'bhora kalan': 'not gurgaon',
    'near nand hospital': 'sector unknown',
    'shivpuri': 'sector 11',
    'jyoti park': 'sector 12',
    'surat nagar phase 2': 'sector 104',
    'rajiv nagar': 'sector 12A',
    'arjun nagar': 'sector 4',
    'ashok vihar phase i': 'sector 5',
    'block h ashok vihar phase iii extension': 'sector 5',
    'devilal colony': 'sector 12A',
    'prem nagar': 'sector 11',
    'bhim nagar': 'sector 14',
    'surat nagar': 'sector 104',
    'gandhi nagar': 'sector 5',
    'khandsa': 'sector 10',
    'ravi nagar': 'sector 5',
    'west rajiv nagar': 'sector 12A',
    'near khandsa road': 'sector 10',
    'sheetla colony': 'sector 5',
    'farukhnagar': 'not gurgaon',
    'mianwali colony': 'sector 12A',
    'lucknow': 'not gurgaon',
    'pataudi road': 'sector 10',
    'shakti nagar': 'sector 6',
    'baldev nagar': 'sector 7',
    'acharya puri': 'sector 7',
    'garhi harsaru': 'sector 36',
    'pratap nagar': 'sector 5',
    'manohar nagar': 'sector 8',
    'vir nagar': 'sector 8',
    'hno 13 sagar enclave sura': 'sector 9',
    'ram nagar': 'sector 8',
    'om nagar': 'sector 10',
    'jacobpura': 'sector 12',
    'tekchand nagar': 'sector 9',
    'ashok vihar phase 3': 'sector 5',
    "ansal's palam vihar": 'sector 1',
    'jacobpura near sadar bazar': 'sector 12',
    'shivji park colony': 'sector 7',
    'udyog vihar phase 1': 'sector 18',
    'mahalaxmi garden, rajendra place': 'sector 7',
    'rattan garden': 'sector 7',
    'sadar bazar': 'sector 12',
    'naharpur rupa': 'sector 12',
    'laxman vihar, railway road,': 'sector 4',
    'sector-5 sheetla colony': 'sector 5',
    'damdma': 'not gurgaon',
    ', delhi ncr': 'not gurgaon',
    'new jyoti park': 'sector 12',
    'sohna  road': 'sector 48',
    'mahavir pura': 'sector 7',
    'park view': 'sector 45',
    'ravi nager basai road': 'sector 9',
    'begampur khatola': 'sector 35',
    'dhankot': 'sector 102',
    'rajiv chowk': 'sector 29',
    'devi lal colony gali no 12 gurgaon nr omkar public school': 'sector 12A',
    'alipur': 'not gurgaon',
    'saraswati enclave': 'sector 28',
    'sec 3 bhim vihar part 1 bhimgher kheri': 'sector 3',
    'near euro': 'sector unknown',
    'bhimgarh kheri phase 3': 'sector 3',
    'huda saraswati vihar': 'sector 28',
    'laxmna vihar, phase 2': 'sector 4',
    'sushant lok phase 2': 'sector 55',
    'ansal plaza': 'sector 56',
    'a block sushant lok phase 1': 'sector 43',
    'mayfield garden': 'sector 47',
    'south city': 'sector 40',
    'rosewood': 'sector 49',
    'v block dlf phase 3': 'sector 24',
    'bissar': 'not gurgaon'
}

In [42]:
# Replace known non-sector locality names with their sector without turning unmatched values into NaN.
df["sector"] = df["sector"].replace(sector_map)

In [43]:
df.sector.value_counts()

sector
sector 48                233
sector 102               122
sector 85                110
sector 92                104
sector 69                 94
                        ...
sector 4 urban estate      1
sector-35 sohna            1
sector-5 sohna             1
sector 37a                 1
sector 42                  1
Name: count, Length: 156, dtype: int64

In [44]:
df.sector.isnull().sum()

np.int64(0)

In [45]:
df.head(5)

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,sector 7,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,...,not_available,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,sector 5,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,...,not_available,"46b, Ashok Vihar, Gurgaon, Haryana",1.0,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,sector 48,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,...,not_available,"Sohna, Gurgaon, Haryana",12.0,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,sector 61,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,...,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2.0,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,sector 92,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,...,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5.0,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [46]:
df.shape

(3961, 21)

In [47]:
df.drop(columns = ["property_name","address"], inplace = True, axis = 1)

In [48]:
df.shape

(3961, 19)

In [49]:
df['society'].fillna('independent', inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_19720\3479342557.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['society'].fillna('independent', inplace=True)

In [50]:
df.to_csv(PROJECT_ROOT / "Data" / "processed" / "Gurgaon_merged.csv", index=False)

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_type    3961 non-null   object
 1   society          3961 non-null   object
 2   sector           3961 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  floorNum         3937 non-null   float64
 12  facing           2784 non-null   object
 13  agePossession    3960 non-null   object
 14  nearbyLocations  3754 non-null   object
 15  description      3961 non-null   object
 16  furnishDetails   2929 non-null   object
 17  features         3252 non-null   object
 18  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(13)
memory usage: 588.1+ KB

In [52]:
df.society.isnull().sum()

np.int64(0)